
image:
  file: .gitpod.Dockerfile
  
tasks:
  - name: Dev Server
    # before: npm install --global http-server
    init: |
      asciibinder build --distro=openshift-enterprise
    command: |
      cd _preview/openshift-enterprise/main
      ln -s welcome/index.html index.html
      python -m http.server
